// importing requirements
const { check } = require('express-validator');

/**
 * This method is only used to validate the _id generated by monogDB fields.
 * @param {Array} mongoIds - This method takes an array of mongoID as input.
 * @param {Boolean} isOptional - provide optional as true, if want the validation array to become optional
 * @returns {Array} - It returns validation array to validate mongoID fields
 */
const validateMongoId = (mongoIds, isOptional) => {

    // check that the given input is array type
    if (!Array.isArray(mongoIds)) throw new Error('This method accepts input as an array only.');

    // now, validating mongo-id
    return mongoIds.map(mongoId => {
        const validationChain = check(mongoId, `Enter a vaild ${mongoId}`).isMongoId()

        // making this field optional
        if (isOptional) validationChain.optional();

        // returning the validation array
        return validationChain;
    })
};

module.exports = { validateMongoId };