// importing requirements
const { check } = require('express-validator');

/**
 * This method is only used to validate the _id generated by monogDB fields.
 * @param {array} mongoIds - This method takes an array of mongoID as input.
 * @param {boolean} isOptional - provide optional as true, if want the validation array to become optional
 * @returns {array} - It returns validation array to validate mongoID fields
 */
const validateMongoId = (mongoIds, isOptional) => {

    // check that the given input is array type
    if (!Array.isArray(mongoIds)) throw new Error('This method accepts input as an array only.');

    // now, validating mongo-id
    return mongoIds.map(mongoId => {
        const validationChain = check(mongoId, `Enter a vaild ${mongoId}`).custom((id) => {
            if (!isValidMongoObjectId(id)) {
                throw new Error('Invalid ObjectId');
            }
            return true; // Return true to indicate the value is valid
        });

        // making this field optional
        if (isOptional) validationChain.optional();

        // returning the validation array
        return validationChain;
    })
};

module.exports = { validateMongoId };